// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//

public class R {
    public enum ImagesAssets: String {
        /// AppIcon
        case app = "AppIcon"
        /// LaunchImage
        case launch = "LaunchImage"
    }
    public enum Strings: String {
    }
}

public extension R.Strings {
    public var localizedValue: String {
        return NSLocalizedString(self.rawValue,
                                 bundle: NSBundle(forClass: R.self),
                                 comment: "")
    }
}

